import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Header from "@/components/ui/header/content";
import Footer from "@/components/ui/footer";
import Banner from "@/components/ui/banner";
import getDictionary, { langs } from "@/dict";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return langs.map((lang) => ({ lang }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<
  {
    children: React.ReactNode;
  } & PageProps
>) {
  const { banner } = await getDictionary(params.lang);
  return (
    <html lang={params.lang} className="light">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Banner dict={banner} />
        <Footer />
      </body>
    </html>
  );
}
